apiVersion: v1
kind: List
items:

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    annotations:
      description: Self-hosted snippet manager
      tags: ruby, rails
    labels:
      app: snibox
    name: snibox

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    labels:
      app: snibox
    name: snibox
  spec:
    successfulBuildsHistoryLimit: 2
    failedBuildsHistoryLimit: 1
    runPolicy: 'Serial' 
    
    triggers:
    - github:
        secret: snibox
      type: GitHub
    - generic:
        secret: snibox
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
      
    source:
      git:
        uri: https://github.com/snibox/snibox.git
        ref: 'master'
      type: Git
    
    strategy:
      sourceStrategy:
        env:
          # database, user etc
          - name: DATABASE_SERVICE_NAME
            value: 'postgresql'
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                key: database-name
                name: snibox-secrets
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: snibox-secrets
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: snibox-secrets
          # rails
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                key: keybase
                name: snibox-secrets
          - name: REQUIRE_RAILS_MASTER_KEY
            value: 'false'
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                key: rails-master-key
                name: snibox-secrets
          - name: WEBPACKER
            value: 'none'
          
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'ubi8-rails:6.0'
          
      type: Source
        
    output:
      to:
        kind: ImageStreamTag
        name: 'snibox:latest'
