apiVersion: v1
items:
- kind: Secret
  apiVersion: "v1"
  metadata:
    name: 'snibox-secrets'
  stringData:
    application-user: 'admin'
    application-user-email: 'admin@example.com'
    application-user-password: 'changeme'
    database-name: 'proddb'
    database-admin-user: 'adminuser'
    database-admin-password: 'changeme'
    database-user: 'dbuser'
    database-password: 'changeme'
    keybase: 'c9a95f4bb21ad02df0ff75183f5079c9ad7c86fcc0d04d5c2be3015d0cc95b47b2fe456eba772e249607b191a4ac147e82c1e4f6bcd5e772174b2067a1adf3a5'
    rails-master-key: 'bd391...'
    smtp-provider-host: 'SMTP_PROVIDER_HOST'
    smtp-provider-domain: 'SMTP_PROVIDER_DOMAIN'
    smtp-provider-username: 'SMTP_PROVIDER_USERNAME'
    smtp-provider-password: 'SMTP_PROVIDER_PASSWORD'
  
kind: List
metadata: []
