apiVersion: v1
items:
  - kind: DeploymentConfig
    apiVersion: "v1"
    metadata:
      annotations:
        description: Defines how to deploy the database
        template.alpha.openshift.io/wait-for-ready: "true"
      name: "postgresql"
      labels:
        app: snibox
    spec:
      replicas: 1
      selector:
        name: "postgresql"
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: "postgresql"
          name: "postgresql"
        spec:
          containers:
            - env:
                # database, user etc
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: snibox-secrets
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: snibox-secrets
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: snibox-secrets
                # db connection parameters
                - name: POSTGRESQL_MAX_CONNECTIONS
                  value: "50"
                - name: POSTGRESQL_SHARED_BUFFERS
                  value: "12MB"

              image: " "
              name: postgresql
              ports:
                - containerPort: 5432

              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 5432
                timeoutSeconds: 1

              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - "-i"
                    - "-c"
                    - >-
                      psql -h 127.0.0.1 -U ${POSTGRESQL_USER} -q -d
                      ${POSTGRESQL_DATABASE} -c 'SELECT 1'
                initialDelaySeconds: 5
                timeoutSeconds: 1

              resources:
                limits:
                  memory: 512Mi

              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: "postgresql-data"
          volumes:
            - name: "postgresql-data"
              persistentVolumeClaim:
                claimName: "database"
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              name: "postgresql:10"
              namespace: "openshift"
          type: ImageChange
        - type: ConfigChange

  - kind: Service
    apiVersion: "v1"
    metadata:
      annotations:
        description: Exposes the database server
      name: "postgresql"
      labels:
        app: snibox
    spec:
      ports:
        - name: "db"
          port: 5432
          targetPort: 5432
      selector:
        name: "postgresql"

kind: List
